version: '3'
services:
  crudgen-db-1:
    image: postgres:latest
    environment:

      POSTGRES_PASSWORD: samplepass
    ports:
      - "5432:5432"
    networks:
      - crudgen

  crudgen-web-1:
    restart: always
    build: .
    ports:
      - "80:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=samplepass
    depends_on:
      - crudgen-db-1
  
    networks:
      - crudgen

networks:
  crudgen:
