version: '3'
services:
  crudgen-db-1:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: samplepass
    ports:
      - "5432:5432"
    networks:
      - crudgen

  crudgen-web-1:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - crudgen-db-1
    networks:
      - crudgen

networks:
  crudgen:
